RA-07 Базовая верстка экрана со списком категорий
bogdantvor/RecepiesApplication pull request #7
Opened 2024-02-28 11:03 UTC by bogdantvor

2024-02-29 06:08 UTC, ievetrovdev requested changes
И еще в MainActivity

1. остался тестовый комментарий 
2. приватные методы лучше располагать в порядке после публичных и переопределенных

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">20sp</item>
отступы и размеры шрифтов тоже следует выносить в ресурсы. пройдись по всем стилям

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="background_title_title">#F4FAFF</color>
Повторять значения одних и тех же цветов с разными айдишниками не рекомендуется. Пусть в ресурсах хранятся только уникальные айтемы, а уникализировать значения для разных элементов интерфейса корректнее через кастомные стили.

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:textSize="12sp" />
тут и во всем файле ресурсы

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +    android:layout_width="160dp"
Лейаут для элемента списка следует заполнять полностью. То есть это верстка не для части экрана, а полноценный элемент списка. В самом списке элемент примет уже соответствующую адаптивную форму.

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="130dp"
Вынести в ресурсы. Все остальные значения в лейауте следует сделать адаптивными. Ширину по родителю, а высота будет по размеру контента, тк описания могут приходить разной длины.

2024-02-29 06:08 UTC, ievetrovdev commented on app/src/main/res/layout/item_category.xml
> +            android:textSize="12sp" />
Давай заполним данные тестовыми данными любого рецепта. Через атрибут tools. Передача отладочных данных в атрибут text может грозить тем, что их увидит пользователь.

2024-03-01 11:03 UTC, ievetrov requested changes

2024-03-01 11:03 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +    android:layout_height="match_parent"
так элемент займет весь экран. делаем только ширину по родителю, а высоту по размеру контента

2024-03-01 11:03 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="@dimen/size_160"
ширина по родителю. весь лейаут по ширине считаем на полноценную карточку

2024-03-01 11:03 UTC, ievetrov commented on app/src/main/res/layout/item_category.xml
> +            android:id="@+id/textView1"
кроме того позаботься, чтобы были отступы по макету у заголовка и описания. чтобы длинный текст не был вплотную к границам или не залезал за

2024-03-01 11:54 UTC, merged