RA-09 List item callback
bogdantvor/RecepiesApplication pull request #9
Opened 2024-03-11 11:40 UTC by bogdantvor

2024-03-12 10:01 UTC, ievetrovdev requested changes

2024-03-12 10:01 UTC, ievetrovdev commented on app/src/main/res/values/colors.xml
> +    <color name="title_title_color">#5F3678</color>
а почему два раза тайтл?)

2024-03-12 10:01 UTC, ievetrovdev commented on app/src/main/java/com/example/recepiesapplication/CategoriesListAdapter.kt
> +            itemClickListener?.onItemClick(category)
Давай передавать не всю категорию, а только айди.

2024-03-12 10:01 UTC, ievetrovdev commented on app/src/main/java/com/example/recepiesapplication/CategoriesListFragment.kt
> +            arguments = Bundle().apply {
Хорошо. Для использования Bundle().apply {} достаточно стандартного API Android.
Но можно использовать более свежий и красивый подход, который нам доступен благодаря ktx библиотеке.
val bundle = bundleOf(ARG_CATEGORY_ID to categoryId)

2024-03-12 10:01 UTC, ievetrovdev commented on app/src/main/java/com/example/recepiesapplication/CategoriesListFragment.kt
> +                putString("categoryId", categoryId.toString())
идентификатор ключа стоит вынести в константу. причем принято это делать в отдельном файле, например Constants.kt

2024-03-12 10:01 UTC, ievetrovdev commented on app/src/main/java/com/example/recepiesapplication/CategoriesListFragment.kt
> +        parentFragmentManager.beginTransaction().apply {
используй способ создания транзакций из MainActivity. он более чистый и актуальный

2024-03-13 11:04 UTC, bogdantvor commented on app/src/main/res/values/colors.xml
> +    <color name="title_title_color">#5F3678</color>
Фантазии по-другому не хватило назвать ) Типа этот элемент у нас это заголовок шапки, то есть как бы тайтл тайтла

2024-03-13 12:07 UTC, ievetrov approved these changes

2024-03-14 12:30 UTC, merged